package com.sigmapensions.sigmamobileapp.utils;

import java.util.ArrayList;

public class States {
	
	public static final String[] TITLES = {"", "ALHAJI", "APOSTLE", "ARCHITECT", "BARRISTER", "BISHOP", "CHIEF", 
		"COMRADE", "DR.", "ENGINEER", "EVANGELIST", "HAJIYA", "HONORABLE", "MALLAM", "MISS", "MR.", "MRS.",  "PASTOR", 
		"PASTOR MRS.", "PROFESSOR", "PROPHET", "PROPHETESS", "REVEREND"};
	
	public static final String[] RELATIONSHIPS = {"N/A", "AUNTY", "BROTHER", "COUSIN", "DAUGHTER", "FATHER", "FRIEND", 
		"GUARDIAN",	"MOTHER", "NEPHEW", "NIECE", "OTHER", "SISTER", "SON", "UNCLE"};
	
	public static final String[] MARRIED = {"MARRIED", "SINGLE", "DIVORCED", "WIDOWED"};
	
	public static final String[] NA = {"N/A"};
		
	public static final String[] STATES = {"N/A", "ABIA", "ADAMAWA", "AKWA IBOM", "ANAMBRA", "BAUCHI",	"BAYELSA", "BENUE",
		"BORNO", "CROSS RIVER",	"DELTA", "EBONYI", "EDO",	"EKITI", "ENUGU", "GOMBE", "IMO", "JIGAWA",	"KADUNA",
		"KANO",	"KATSINA",	"KEBBI", "KOGI", "KWARA", "LAGOS",	"NASARAWA",	"NIGER", "OGUN", "ONDO", "OSUN",
		"OYO",	"PLATEAU",	"RIVERS",	"SOKOTO",	"TARABA",	"YOBE",	"ZAMFARA"};
	
	
	public static final String[] ABIA = {"ABA  NORTH", "ABA  SOUTH", "AROCHUKWU", "BENDE", "IKAWUNO", "IKWUANO", "ISIALANGWA  NORTH", 
		"ISIALANGWA", " SOUTH", "ISIKWUATO", "ISUIKWUATO", "NNEOCHI", "OBI NGWA", "OBI NGWA", "OBIOMA NGWA", "OBIOMANGWA",
		"OHAFIA", "OHAOZARA", "OSISIOMA", "UGWUNAGBO", "UKWA  WEST", "UKWU  EAST", "UMUAHIA", "UMUAHIA  NORTH", "UMUAHIA  SOUTH", 
		"UMUAHIA NORTH", "UMUNNEOCHI"};
	
	public static final String[] ADAMAWA = {"DEMSA",  "FUFORE",  "GANYE",  "GIREI",  "GOMBI",  "GUYUK",  "HONG",  "JADA", 
		"JIMETA",  "LAMURDE",  "MADAGALI",  "MAIHA",  "MAYOBELWA", "MICHIKA", "MUBI NORTH", "MUBI SOUTH",
		"NUMAN",  "SHELLENG",  "SONG",  "TOUNGO",  "YOLA"};
	
	public static final String[] AKWA_IBOM = {"ABAK",  " EASTERNOBOLO", "EKET",  "EKPEATANI", "ESIT EKIT",  "ESSIENUDIM",
		"ETIMEKPO",	"ETINAM",  "IBENO",  "IBESIKPOASUTAN",	"IBIONOIBOM", "IKA",  "IKONO",  "IKOTABASI",
		"IKOTEKPENE", "INI",  "ITU",  "MBO",  "MKPATENIN",	"NSITIBOM",	"NSITUBIUM", "OBOTAKARA", "OKOBO", 	"ONNA",  
		"ORON",  "ORUK ANAM",  "UDUNGUKO",	"UKANEFUN",  "UQUO IBENO",  "URU OFFONG ORUKO",  "URUAN",  "URUKANAM", "UYO"};
	
	public static final String[] ANAMBRA = {"AGUATA",  "AKWA  NORTH",  "ANAMBRA",  "ANAMBRA WEST", "ANAOCHA",  "AWKA NORTH",
		"AWKA SOUTH", "AYAMELUM",  "DUNUKOFIA",  "EKWUSIGO", "IDEMILI",  "IDEMILI NORTH", "IDEMILI SOUTH",	"IHIALA",  "IMO",  
		"NIBO",  "NJIKOKA",  "NNEWI",  "NNEWI NORTH", "NNEWI SOUTH", "OGBARU",  "OLUMBA", "ONITSHA NORTH", "ONITSHA SOUTH",
		"ORUMBA NORTH", "ORUMBA SOUTH", "OTI",  "OTUOCHA", "UBULUIZOR IHIALA",  "UYI"};
	
	public static final String[] BAUCHI = {"ALKALERI",  "BAUCHI",  "BOGORO",  "DAMBAN",  "DARAZO",  "DASS",  "GAMAWA",  
		"GANJUWA",  "GIADE",  "ITAS/GADAU",  "JAMA'ARE",  "KATAGUM",  "KIRFI", "MISAU",  "NINGI",  "SHIRA",  "TAFAWABALEWA",
		"TORO",  "WARJI",  "ZAKI"};
	
	public static final String[] BAYELSA = {"ADAGBABIRI", "BRASS", "EKEREMOR", "KEMBE", "KOLOKUMA", "KOLOKUMA/OPKUMA", "NEMBE", "OGBIA", 
		"SAGBAMA", " SOUTHERNIJAW", "TORUABUBO",	"YENEGOA"};
	
	public static final String[] BENUE = {"ADO", "AGATU", "APA", "BURUKU", "GBOKO", "GUMA", "GWER EAST",	"GWER WEST",
		"KATSINAALA", "KONSHISHA", "KWANDE", "LOGO", "MAKURDI", "OGBADIBO", "OHIMINI", "OJU", "OKPOKWU", "OTUKPO", 
		"OTURKPA", "TARKA", "UKUM", "USHONGO", "VANDEIKYA"};
	
	public static final String[] BORNO = {"ABADAN", "ASKIRAUBA", "BAMA", "BAYO", "BIU", "CHIBOK", "DAMBOA", "DIKWA", 
		"GUBIO", "GUZAMALA", "GWOZA", "HAWUL", "JERE", "KAGA", "KALA/BALGE", "KONDUGA", "KUKAWA", "KWAYAKUSAR",
		"MAFA", "MAGUMERI", "MAIDUGURI", "MARTE", "MOBBAR", "MONGUNU", "NGALA", "NGANZAI", "SHANI"};
	
	public static final String[] CROSS_RIVER = {"ABI", "ABUOCHICHIE", "AKAMKPA", "AKPABUYO", "BAKASSI", "BEKWARA", 
		"BIASI", "BOKI", "CALABARMUNICIPAL", "CALABAR SOUTH", "ETUNK", "IKOM", "OBANLIKU", "OBUBRA", "OBUDU", "ODUKPANI", 
		"OGOJA", "UGEP NORTH", "YAKURR", "YALA"};
	
	public static final String[] DELTA = {"ANIOCHA  NORTH", "ANIOCHA NORTH", "ANIOCHA SOUTH", "BOMADI", "BURUTU", 
		"EFFURUN", "ETHIOPE EAST", "ETHIOPE WEST", "IDU", "IKANE", "IKA  NORTH EAST", "IKA SOUTH", "IKPEMILI", "ISOKO NORTH",
		"ISOKO SOUTH", "NDOKWA EAST", "NDOKWA NORTH", "NDOKWA SOUTH", "NDOKWA WEST", "OKPE", "OKWUANI", "OLEH", "OSHIELLI NORTH",
		"OSHIMILI", "OSHIMILI NORTH", "OSHIMILI SOUTH", "OSIMILI", "OSIMILI NORTH", "OSIMILI SOUTH", "PATANI", "SAPELE", 
		"UDOKWA", "UDU", "UGHELLI NORTH", "UGHELLI SOUTH", "UKWUANI", "URAUN", "URWIE", "UVIE", "UVWEI", "WARRI CENTRAL",
		"WARRI NORTH", "WARRI SOUTH"};
	
	public static final String[] EBONYI = {"ABAKALIKI", "AFIKPO NORTH", "AFIKPO SOUTH", "BOMADIM", "EBONYI", "EZZA NORTH",
		"EZZA SOUTH", "IKWO", "ISHIELU", "IVO", "IZZI", "OBAUKWU", "OHAKWU", "ONICHA", "UKABA"};
	
	public static final String[] EDO = {"AFOKPELLA", "AFUZE", "AGBAZILO", "AKOKO EDO", "AKOKOEDO", "EGOR", "ESAN CENTRAL",
		"ESAN  NORTH EAST", "ESAN  NORTH EAST", "ESAN  SOUTH EAST", "ESAN WEST", "ETSAKO CENTRAL", "ETSAKO EAST", "ETSAKO WEST",
		"IGUEBEN", "IGUOBANO  NORTH  EAST", "IKPOBAOKHA", "OHUNMWODE", "OLOGBO", "OPOJI IRRUA", "OPOJI IRRUA", "OREDO", 
		"ORHIONMWON", "OVIA  NORTH EAST", "OVIA  SOUTH WEST", "OWAN  EAST", "OWAN EAST", "OWAN WEST", "UHUNMWONDE"};
	
	public static final String[] EKITI = {"ADOEKITI", "AIYEKIRE", "EFON", "EKITI EAST", "EKITI  SOUTH WEST", "EKITI WEST",
		"EMURE/ISE/ORUN", "GBONYIN", "IDOOSI", "IJERO", "IKARE", "IKERE", "IKOLE", "ILEJEMEJE", "IREPODUN/IFELODUN", 
		"ISEORUN", "MOBA", "OYE"};
	
	public static final String[] ENUGU = {"ANINRI", "AWGU", "ENUGU EAST", "ENUGU NORTH", "ENUGU SOUTH", "EZEAGU", "IGBOETITI",
		"IGBOEZE NORTH", "IGBOEZE SOUTH", "ISIUZO", "NKANU EAST", "NKANU WEST", "NSUKKA", "NUKANU  EAST", "OJIRIVER",
		"UDENU", "UDI", "UZOUWANI"};
	
	public static final String[] GOMBE = {"AKKO", "BALANGA", "BILLIRI", "DUKKU", "FUNAKAYE", "GOMBE", "KALTUNGO", "KWAMI", 
		"NAFADA/BAJOGA", "SHOMGOM", "YAMALTU/DEBA"};
	
	public static final String[] IMO = {"ABOHMBAISE", "AHIAZUMBAISE", "DRALESAT", "EHIMEMBANO", "EZEOBODO", "EZINIHITTE", 
		"IDEATO", "IDEATO NORTH", "IDEATO SOUTH", "IHITTE/UBOMA", "IKEDURU", "ISIALAMBANO", "ISU", "MBAITOLI", "MBANO", 
		"NGOROKPALA", "NJABA", "NKWERRE", "NWANGELE", "OBOWO", "OGUTA", "OHAJIEGBEMA", "OKIGWE", "ONUIMO", "ORLU", 
		"ORO WEST", "ORSU", "ORU EAST", "ORU WEST", "OWERRIMUNICIPAL", "OWERRI NORTH", "OWERRI WEST", "UGIRIIKE", "IKEDURU", 
		"UGIRIIKEDIKEDURU", "UNBANO", "ZINIHITTE"};
	
	public static final String[] JIGAWA = {"AUYO", "BABURA", "BIRINIWA", "BIRNINKUDU", "BOSUWA", "BUJI", "DUTSE", 
		"GAGARAWA", "GARKI", "GUMEL", "GURI", "GWARAM", "GWIWA", "HADEJIA", "JAHUN", "KAFINHAUSA", "KAUGAMA", "KAZAURE", 
		"KIRKASAMMA", "MAIGATARI", "MALAMMADURI", "MIGA", "RINGIM", "RONI", "SULETANKARKAR", "TAURA", "YANKWASHI"};
	
		
	public static final String[] KADUNA = {"BIRNINGWARI", "CHIKUN", "GIWA", "GWAGWADA", "IGABI", "IKARA", "JABA", 
		"JEMA'A", "KACHIA", "KADUNA NORTH", "KAGARKO", "KAJURU", "KAURA", "KAURU", "KOKA/KAWO", "KUBAH", "KUDAN", "LERE", 
		"MAKARFI", "SABONGARI", "SANGA", "SOBA", "TUDUNWADA/MAKERA", "ZANGOKATAF", "ZARIA"};
	
	public static final String[] KANO = {"AJINGI", "ALBASU", "BAGWAI", "BEBEJI", "BICHI", "BUNKURE", "DALA", "DAMBATTA",
		"DAWAKINKUDU", "DAWAKINTOFA", "DOGUWA", "FAGGE", "GABASAWA", "GARKO", "GARUNMALLAM", "GAYA", "GEZAWA", "GWALE", 
		"GWARZO", "KANO MUNICIPAL", "KARAYE", "KIBIYA", "KIRU", "KUMBOTSO", "KUNCHI", "KURA", "MADOBI", "MAKODA", 
		"MINJIBIR", "NASARAWA", "RANO", "RIMINGADO", "ROGO", "SHANONO", "SUMAILA", "TAKAI", "TARAUNI", "TOFA", 
		"TSANYAWA", "TUDUNWADA", "UNGOGO", "WARAWA", "WUDIL"};
	
	public static final String[] KATSINA = {"BAKORI", "BATAGARAWA", "BATSARI", "BAURE", "BINDAWA", "CHARANCHI", "DANMUSA", 
		"DANDUME", "DANJI", "DAURA", "DUTSI", "DUTSINMA", "FASKARI", "FUNTUA", "INGAWA", "JIBIA", "KAFUR", "KAITA", "KANKARA", 
		"KANKIA", "KATSINA", "KURFI", "KUSADA", "MAIADUA", "MALUMFASHI", "MANI", "MASHI", "MATAZU", "MUSAWA", "RIMI", "SABUWA",
		"SAFANA", "SANDAMU", "ZANGO"};
	
	public static final String[] KEBBI = {"ALEIRO", "AREWADANDI", "ARGUNGU", "AUGIE", "BAGUDO", "BIRNINKEBBI", "BUMZA", 
		"DANDI", "DANKO", "FAKAI", "GWANDU", "JEGA", "KALGO", "KOKOBESSE", "MAIYAMA", "NGASKI", "SAKABA", "SHANGA", 
		"SURU", "WASAGU", "YAURI", "ZURU"};
	
	public static final String[] KOGI = {"ADAVI", "AJAOKUTA", "ANKPA", "DEKINA", "IBAJI", "IDAH", "IGALAMELA", "IJUMU",
		"IKOYIIJUMU", "KABBA/BUNU", "KOGI", "LOKOJA", "MOPAMUROMOPI", "OBAJI", "OFU", "OGORI/MAGONGO", "OKEHI", "OKENE", 
		"OLAMABORO", "OMALA", "ORU", "OYI", "YAGBA EAST", "YAGBA WEST"};
	
	public static final String[] KWARA = {"ASA", "BARUTEN", "EDU", "EKITI", "ILORIN EAST", "ILORIN SOUTH", "ILORIN WEST",
		"ISIN", "KAIAMA", "MORO", "OFFA", "OKEERO", "OYUN", "PATEGI"};
	
	public static final String[] LAGOS = {"AGEGE", "AJEROMIIFELODUN", "ALIMOSHO", "AMUWOODOFIN", "APAPA", "BADAGRY", 
		"EPE", "ETIOSA", "IBEJULEKKI", "IFAKOIJAIYE", "IKEJA", "IKORODU", "ISLAND", "KOSOFE", "LAGOSISLAND", 
		"LAGOSMAINLAND", "MUSHIN", "OJO", "OSHODIISOLO", "SHOMOLU", "SOMOLU", "SURULERE", "YEWA SOUTH"};
	
	public static final String[] NASSARAWA = {"AKWANGA", "AWE", "DOMA", "KARU", "KEANA", "KEFFI", "KOKONA", "LAFIA", 
		"NASSAWARA", "NASSAWARA EGGON", "OBI", "WAMBU"};
	
	public static final String[] NIGER = {"AGAIE", "AGWARA", "BIDA", "BORGU", "BOSSO", "CHANCHAGA", "EDATI", "GBAKO", 
		"GURARA", "KATCHA", "KONTAGORA", "LAPAI", "LAVUN", "MAGAMA", "MARIGA", "MASHEGU", "MINNA", "MOKWA", "MUYA", "PAIKORO", 
		"RAFI", "RIJAU", "SHIRORO", "SULEJA", "TAFA", "WUSHISHI"};
	
	public static final String[] OGUN = {"ABEOKUTA NORTH", "ABEOKUTA SOUTH", "ABOR MBAISE", "ADOODO/OTA", "ADOODOOTA",
		"EWEKORO", "IDARAPO", "IFFOOTTA", "IFO", "IGBADO NORTH", "IGBADO SOUTH", "IJEBU EAST", "IJEBU NORTH", "IJEBU  NORTH EAST",
		"IJEBUODE","IKENNE", "ILISHAN REMO", "ILUGUNALARO", "IMEKOAFON", "IPOKIA", "LGAYEKPE", "OBAFEMIOWODE", "ODEDAH", 
		"ODOGBOLU", "OGUNWATERSIDE", "REMO NORTH", "SAGAMU", "SHAGAMU", "YEWA"};
	
	public static final String[] ONDO = {"AKOKO", "AKOKO NORTH", "AKOKO    NORTH WEST", "AKOKO SOUTH", "AKOKO  SOUTH EAST", "AKURE", 
		"AKURE NORTH", "AKURE SOUTH", "ESEODO", "IDANRE", "IFEDORE", "IGBISIN", "IKALE", "ILAJE", "ILAJE WEST", 
		"ILEOLUJIOKEIGBO", "IRELE", "ODIGBO", "OKA AK0KO", "OKITI PUPA IJUODO", "OKITIPUPA", "ONDO", "ONDO  WEST", 
		"ONDO EAST", "OSE", "OWO"};
	
	public static final String[] OSUN = {"ATAKUMOSA", "ATAKUMOSA  EAST", "AYEDAADE", "AYEDIRE", "BOLUWADURO", "BORIPE",
		"EDE", "EDE  NORTH", "EGBEDORE", "EJIGBO", "IFE", "IFE  NORTH", "IFE  SOUTH", "IFE CENTRAL", "IFE EAST", "IFELODUN", 
		"ILA", "ILESA EAST", "ILESA WEST", "ILESHA", "ILESHA  WEST", "IREPODUN", "IREWOLE", "ISOKAN", "IWO", "OBOKUN", 
		"ODOOTIN", "OLA OLUWA", "OLORUNDA", "ORIADE", "OROLU", "OSOGBO"};
	
	public static final String[] OYO = {"AFIJIO", "AKINYELE", "ATIBA", "ATIGBO", "EGBEDA", "IBADAN CENTRAL", 
		"IBADAN  NORTH EAST", "IBADAN  NORTH WEST", "IBADAN  SOUTH EAST", "IBADAN  SOUTH WEST", "IBARAPA CENTRAL", "IBARAPA EAST",
		"IBARAPA NORTH", "IDO", "IFEDAYO", "IFELOJU", "IREPO", "ISEYIN", "ITSEIWAJU", "IWAJOWA", "KAJOLA", "LAGELU", 
		"ODOOLUWA", "OGBOMOSHO NORTH", "OGBOMOSHO SOUTH", "OLORUNSOGO", "OLUYOLE", "ONAARA", "ORELOPE", "ORIIRE", 
		"OYO WEST", "SAKI EAST", "SAKI WEST", "SURULERE"};
	
	public static final String[] PLATEAU = {"BARKINLADI", "BASSA", "BOKKOS", "JOS EAST", "JOS NORTH", "JOS SOUTH", "KANAM", 
		"KANKE", "LANGTANG NORTH", "LANGTANG SOUTH", "MANGU", "MIKANG", "PANKSHIN", "QUAN'ANPAN", "RIYOM", "SHENDAM", 
		"WASE"};
	
	public static final String[] RIVERS = {"ABOA/ODUAL", "AHOADA EAST", "AHOADA WEST", "AKUKUTORU", "ANDONI", "ASARITORU",
		"BONNY", "BUGUMA", "DEGEMA", "ELEME", "ELFANE", "EMUOHA", "ETCHE", "GOKANA", "IKWERRE", "KHANA", "OBIA/AKPOR", 
		"OGBAEGBEMANDONI", "OGBA/EGBEMA/NDONI", "OGU/BOLO", "OKIRIKA", "OMUMA", "OPOBO/NKORO", "OYIGBO", "PORTHARCOURT",
		"TAI"};
	
	public static final String[] SOKOTO = {"BINJI", "BODINGA", "DANGESHUNI", "GADA", "GORONYO", "GUDU", "GWADABAWA", 
		"ILLELA", "KEBBE", "KWARE", "RABA", "SABOBIRNI", "SHAGARI", "SILAME", "SOKOTO NORTH", "SOKOTO SOUTH", "TAMBUWAL", 
		"TANGAZA", "TURETA", "WAMAKKO", "WURNO", "YABO"};
	
	public static final String[] TARABA = {"ARDOKOLA", "BALI", "DONGA", "GASHAKA", "GASSOL", "IBI", "JALINGO", 
		"KARIMLAMIDO", "KURMI", "LAU", "OILINGO", "SARDAUNA", "TAKUM", "USSA", "WUKARI", "YORRO", "ZING"};
	
	public static final String[] YOBE = {"BADE", "BORSALI", "DAMATURU", "FIKA", "FUNE", "GEIDAM", "GOGARAM", "GUJBA", 
		"GULANI", "JAKUSKO", "KARASUWA", "MACHINA", "NANGERE", "NGURU", "POTISKUM", "TARMUA", "YUNUSARI", "YUSUFARI"};
	
	public static final String[] ZAMFARA = {"ANKA", "BAKURA", "BUKKUYUM", "BUNGUDU", "GUMI", "GUSAU", "ISA", 
		"KAURANAMODA", "KIYAWA", "MARADUN", "MARU", "SHINKAFI", "TALATAMAFARA", "TSAFE", "ZURMI"};
	
	public static final String[] COUNTRIES = {
		"AFGHANISTAN",
		"ALBANIA",
		"ALGERIA",
		"ANDORRA",
		"ANGOLA",
		"ANTIGUA AND BARBUDA",
		"ARGENTINA",
		"ARMENIA",
		"AUSTRALIA",
		"AUSTRIA",
		"AZERBAIJAN",
		"BAHAMAS",
		"BAHRAIN",
		"BANGLADESH",
		"BARBADOS",
		"BELARUS",
		"BELGIUM",
		"BELIZE",
		"BENIN",
		"BHUTAN",
		"BOLIVIA",
		"BOSNIA AND HERZEGOVINA",
		"BOTSWANA",
		"BRAZIL",
		"BRUNEI",		
		"BULGARIA",
		"BURKINA FASO",
		"BURUNDI",		
		"CABO VERDE",
		"CAMBODIA",
		"CAMEROON",
		"CANADA",
		"CENTRAL AFRICAN REPUBLIC",
		"CHAD",
		"CHILE",
		"CHINA",
		"COLOMBIA",
		"COMOROS",
		"CONGO, REPUBLIC OF THE",
		"CONGO, DEMOCRATIC REPUBLIC OF THE",
		"COSTA RICA",
		"COTE D'IVOIRE",
		"CROATIA",
		"CUBA",
		"CYPRUS",
		"CZECH REPUBLIC",
		"DENMARK",
		"DJIBOUTI",
		"DOMINICA",
		"DOMINICAN REPUBLIC",
		"ECUADOR",
		"EGYPT",
		"EL SALVADOR",
		"EQUATORIAL GUINEA",
		"ERITREA",
		"ESTONIA",
		"ETHIOPIA",
		"FIJI",
		"FINLAND",
		"FRANCE",
		"GABON",
		"GAMBIA",
		"GEORGIA",
		"GERMANY",
		"GHANA",
		"GREECE",
		"GRENADA",
		"GUATEMALA",
		"GUINEA",
		"GUINEABISSAU",
		"GUYANA",
		"HAITI",
		"HONDURAS",
		"HUNGARY",
		"ICELAND",
		"INDIA",
		"INDONESIA",
		"IRAN",
		"IRAQ",
		"IRELAND",
		"ISRAEL",
		"ITALY",
		"JAMAICA",
		"JAPAN",
		"JORDAN",
		"KAZAKHSTAN",
		"KENYA",
		"KIRIBATI",
		"KOSOVO",
		"KUWAIT",
		"KYRGYZSTAN",
		"LAOS",
		"LATVIA",
		"LEBANON",
		"LESOTHO",
		"LIBERIA",
		"LIBYA",
		"LIECHTENSTEIN",
		"LITHUANIA",
		"LUXEMBOURG",
		"MACEDONIA",
		"MADAGASCAR",
		"MALAWI",
		"MALAYSIA",
		"MALDIVES",
		"MALI",
		"MALTA",
		"MARSHALL ISLANDS",
		"MAURITANIA",
		"MAURITIUS",
		"MEXICO",
		"MICRONESIA",
		"MOLDOVA",
		"MONACO",
		"MONGOLIA",
		"MONTENEGRO",
		"MOROCCO",
		"MOZAMBIQUE",
		"MYANMAR (BURMA)",
		"NAMIBIA",
		"NAURU",
		"NEPAL",
		"NETHERLANDS",
		"NEW ZEALAND",
		"NICARAGUA",
		"NIGER",
		"NIGERIA",
		"NORTH KOREA",
		"NORWAY",
		"OMAN",
		"PAKISTAN",
		"PALAU",
		"PALESTINE",
		"PANAMA",
		"PAPUA NEW GUINEA",
		"PARAGUAY",
		"PERU",
		"PHILIPPINES",
		"POLAND",
		"PORTUGAL",
		"QATAR",
		"ROMANIA",
		"RUSSIA",
		"RWANDA",
		"ST. KITTS AND NEVIS",
		"ST. LUCIA",
		"ST. VINCENT AND THE",
		"GRENADINES",
		"SAMOA",
		"SAN MARINO",
		"SAO TOME AND PRINCIPE",
		"SAUDI ARABIA",
		"SENEGAL",
		"SERBIA",
		"SEYCHELLES",
		"SIERRA LEONE",
		"SINGAPORE",
		"SLOVAKIA",
		"SLOVENIA",
		"SOLOMON ISLANDS",
		"SOMALIA",
		"SOUTH AFRICA",
		"SOUTH KOREA",
		"SOUTH SUDAN",
		"SPAIN",
		"SRI LANKA",
		"SUDAN",
		"SURINAME",
		"SWAZILAND",
		"SWEDEN",
		"SWITZERLAND",
		"SYRIA",
		"TAIWAN",
		"TAJIKISTAN",
		"TANZANIA",
		"THAILAND",
		"TIMORLESTE",
		"TOGO",
		"TONGA",
		"TRINIDAD AND TOBAGO",
		"TUNISIA",
		"TURKEY",
		"TURKMENISTAN",
		"TUVALU",
		"UGANDA",
		"UKRAINE",
		"UNITED ARAB EMIRATES",
		"UNITED KINGDOM (UK)",
		"UNITED STATES OF AMERICA (USA)",
		"URUGUAY",
		"UZBEKISTAN",
		"VANUATU",
		"VATICAN CITY (HOLY SEE)",
		"VENEZUELA",
		"VIETNAM",
		"YEMEN",
		"ZAMBIA",
		"ZIMBABWE"		
		};
	
	public static ArrayList<String[]> LGA; 
	
	public States(){
		LGA = new ArrayList<String[]>();
		
		LGA.add(NA);
		LGA.add(ABIA);
		LGA.add(ADAMAWA);
		LGA.add(AKWA_IBOM);
		LGA.add(ANAMBRA);
		LGA.add(BAUCHI);
		LGA.add(BAYELSA);
		LGA.add(BENUE);
		LGA.add(BORNO);
		LGA.add(CROSS_RIVER);
		LGA.add(DELTA);
		LGA.add(EBONYI);
		LGA.add(EDO);
		LGA.add(EKITI);
		LGA.add(ENUGU);
		LGA.add(GOMBE);
		LGA.add(IMO);
		LGA.add(JIGAWA);
		LGA.add(KADUNA);
		LGA.add(KANO);
		LGA.add(KATSINA);
		LGA.add(KEBBI);
		LGA.add(KOGI);		
		LGA.add(KWARA);
		LGA.add(LAGOS);
		LGA.add(NASSARAWA);
		LGA.add(NIGER);
		LGA.add(OGUN);
		LGA.add(ONDO);
		LGA.add(OSUN);
		LGA.add(OYO);
		LGA.add(PLATEAU);
		LGA.add(RIVERS);
		LGA.add(SOKOTO);
		LGA.add(TARABA);
		LGA.add(YOBE);
		LGA.add(ZAMFARA);
	}

}
